/**
 * Autogenerated by Thrift Compiler (0.15.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

library Test_HelloThrift;

export 'src/request.dart' show Request;
export 'src/request2.dart' show Request2;
export 'src/response.dart' show Response;
export 'src/hello_service.dart' show HelloService;
export 'src/hello_service.dart' show HelloServiceClient;
export 'src/hello_service.dart' show HelloServiceProcessor;
